siteTitle = "Jon Heslop"
siteHeadline = "I make things for the internet"
siteDescr = "Jon Heslop is a designer & developer based in London."
siteAuthor = "Jon Heslop"
siteImage = "http://jonheslop.com/jon-heslop-face-square.jpg"
siteURL = "http://jonheslop.com/"

googleAnalyticsId = "UA-3354664-1"

linkPrefix = ""

socialTwitterURL = "https://twitter.com/jonheslop"
socialInstgramURL = "https://www.instagram.com/jonheslop/"
socialLinkedInURL = "https://www.linkedin.com/in/jon-heslop/"
