siteTitle = "Jon Heslop"
siteHeadline = "I make things for the internet"
siteDescr = "Jon Heslop is a designer & developer based in London."
siteAuthor = "Jon Heslop"
siteImage = "https://jonheslop.github.io/jfh-gatsby/jon-heslop-face-square.jpg"
siteURL = "https://jonheslop.github.io/jfh-gatsby/"

googleAnalyticsId = "UA-3354664-1"

linkPrefix = ""

socialTwitterURL = "https://twitter.com/jonheslop"
socialInstgramURL = "https://www.instagram.com/jonheslop/"
socialLinkedInURL = "https://www.linkedin.com/in/jon-heslop-b13512b3/"
