siteTitle = "Jon Heslop"
siteHeadline = "I make things for the internet"
siteDescr = "Jon Heslop is a designer & developer based in London."
siteAuthor = "Jon Heslop"

googleAnalyticsId = "UA-3354664-1"

linkPrefix = "/jfh-gatsby"
