siteTitle = "Jon Heslop"
siteHeadline = "I make things for the internet"
siteDescr = "Jon Heslop is a designer & developer based in London."
siteAuthor = "Jon Heslop"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/"
